In [1]:
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from webdriver_manager.firefox import GeckoDriverManager
from bs4 import BeautifulSoup
import csv
import pandas as pd
import time

options = Options()
options.headless = True
driver = webdriver.Firefox(firefox_binary="C:/Program Files/LibreWolf/librewolf.exe", options=options, executable_path=GeckoDriverManager().install())

df = pd.DataFrame(columns=["Number", "Title", "Year", "Runtime", "Genre", "Rating", "Budget", "Votes", "Metascore"])

url_template = "https://www.imdb.com/search/title/?genres=sci-fi&start={}&explore=title_type,genres&title_type=movie&ref_=adv_explore_rhs&language=en"
start = 1
movies = []

# sadece ilk 2 sayfanın verisini almak için döngüyü 2 kez çalıştırıyoruz
for start in range(1, 6001, 50):
    url = url_template.format(start)
    driver.get(url)
    time.sleep(6)
    soup = BeautifulSoup(driver.page_source, 'html.parser')
    
    items = soup.select('.lister-item-content')
    if not items:
        break


    for item in soup.select('.lister-item-content'):
        number = item.select_one('.lister-item-header span').text.strip('()')
        title = item.select_one('.lister-item-header a').text.strip()
        runtime_element = item.select_one('.runtime')
        runtime = runtime_element.text.strip() if runtime_element else ''
        rating_element = item.select_one('.ratings-imdb-rating strong')
        rating = rating_element.text.strip() if rating_element else ''
        year = item.select_one('.lister-item-content .text-muted').text.strip()

        genre_element = item.select_one('.genre')
        genre = " - ".join(genre_element.text.strip().split(',')) if genre_element else ''

        # Metascore bilgisini alınacaktır.
        metascore_element = item.select_one('.metascore')
        metascore = metascore_element.text.strip() if metascore_element else ''


        link = item.select_one('.lister-item-header a')['href']
        driver.get(f"https://www.imdb.com{link}business")
        time.sleep(1)

        soup = BeautifulSoup(driver.page_source, 'html.parser')
            
        # Oyların sayısı alınacaktır.
        votes_element = item.select_one('span[name="nv"]')
        if votes_element:
            votes = votes_element['data-value']
        else:
            votes = ''
        
        # Budget değeri varsa alınacak eğer tahmini varsa o da alınacaktır.
        soup = BeautifulSoup(driver.page_source, 'html.parser')
        budget_elements = soup.findAll('span', {'class': 'ipc-metadata-list-item__list-content-item'})
        budget = ''
        for element in budget_elements:
            text = element.text.strip()
            if text.startswith('$'):
                if any(x in text.lower() for x in ["gross worldwide", "gross us & canada", "opening weekend us & canada"]):
                    continue
                else:
                    if "Budget" in text.lower() or "estimated" in text.lower():
                        budget = text.split(' (')[0]
                        break
                    else:
                        budget = ''
            elif "Budget" in text.lower() or "estimated" in text.lower():
                    budget = text.split(' (')[0]
                    break
            else:
                budget = ''

        df = pd.concat([df, pd.DataFrame({"Number": number, "Title": title, "Year": year, "Runtime": runtime, "Genre": genre, "Rating": rating, "Budget": budget, "Votes": votes, "Metascore": metascore}, index=[0])], ignore_index=True)
        df.to_csv("imdb_scraped_data_scifi.csv", index=False)
driver.quit()

C:\Users\Sw4yt\AppData\Local\Temp\ipykernel_13136\3063400552.py:11: DeprecationWarning: headless property is deprecated, instead use add_argument('-headless')
  options.headless = True
[WDM] - Downloading: 19.2kB [00:00, 9.81MB/s]
[WDM] - Downloading: 19.2kB [00:00, 9.89MB/s]
[WDM] - Downloading: 100%|██████████| 1.59M/1.59M [00:00<00:00, 4.60MB/s]
C:\Users\Sw4yt\AppData\Local\Temp\ipykernel_13136\3063400552.py:12: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Firefox(firefox_binary="C:/Program Files/LibreWolf/librewolf.exe", options=options, executable_path=GeckoDriverManager().install())
C:\Users\Sw4yt\AppData\Local\Temp\ipykernel_13136\3063400552.py:12: DeprecationWarning: firefox_binary has been deprecated, please pass in a Service object
  driver = webdriver.Firefox(firefox_binary="C:/Program Files/LibreWolf/librewolf.exe", options=options, executable_path=GeckoDriverManager().install())

KeyboardInterrupt

In [2]:
df

,Number,Title,Year,Runtime,Genre,Rating,Budget,Votes,Metascore
0,1.,The Hunger Games: The Ballad of Songbirds and ...,(2023),,Action - Adventure - Drama,,,,
1,2.,The Flash,(2023),,Action - Adventure - Fantasy,,"$200,000,000",,
2,3.,Guardians of the Galaxy Vol. 3,(2023),150 min,Action - Adventure - Comedy,8.4,,35997,65
3,4.,Ant-Man and the Wasp: Quantumania,(2023),124 min,Action - Adventure - Comedy,6.2,"$200,000,000",126234,48
4,5.,Transformers: Rise of the Beasts,(2023),,Action - Adventure - Sci-Fi,,"$200,000,000",,
...,...,...,...,...,...,...,...,...,...
5721,"5,722.",Way Station,,,Sci-Fi,,,,
5722,"5,723.",Fallen Cards,,,Action - Adventure - Drama,,"$1,000,000",,
5723,"5,724.",Bimbo bambino,(2018),,Action - Comedy - Drama,6.4,"SEK 100,000",21,
5724,"5,725.",Virus X,(2010),85 min,Horror - Sci-Fi,2.9,"$900,000",611,
5725,"5,726.",Gogola,(1966),,Sci-Fi,8.2,,14,

In [3]:
df.head(55)

,Number,Title,Year,Runtime,Genre,Rating,Budget,Votes,Metascore
0,1.,The Hunger Games: The Ballad of Songbirds and ...,(2023),,Action - Adventure - Drama,,,,
1,2.,The Flash,(2023),,Action - Adventure - Fantasy,,"$200,000,000",,
2,3.,Guardians of the Galaxy Vol. 3,(2023),150 min,Action - Adventure - Comedy,8.4,,35997,65
3,4.,Ant-Man and the Wasp: Quantumania,(2023),124 min,Action - Adventure - Comedy,6.2,"$200,000,000",126234,48
4,5.,Transformers: Rise of the Beasts,(2023),,Action - Adventure - Sci-Fi,,"$200,000,000",,
5,6.,Avatar: The Way of Water,(2022),192 min,Action - Adventure - Fantasy,7.7,"$350,000,000",372123,67
6,7.,Mighty Morphin Power Rangers: Once & Always,(2023),55 min,Action - Adventure - Family,5.8,,4766,61
7,8.,Everything Everywhere All at Once,(2022),139 min,Action - Adventure - Comedy,7.9,"$14,300,000",438661,81
8,9.,65,(2023),93 min,Action - Adventure - Drama,5.4,"$45,000,000",39416,40
9,10.,Nope,(2022),130 min,Horror - Mystery - Sci-Fi,6.8,"$68,000,000",224352,77
10,11.,Dune: Part Two,(2023),,Action - Adventure - Drama,,,,
11,12.,Infinity Pool,(2023),117 min,Crime - Horror - Mystery,6.1,,28331,72
12,13.,Interstellar,(2014),169 min,Adventure - Drama - Sci-Fi,8.6,"$165,000,000",1899414,74
13,14.,Super Mario Bros.,(1993),104 min,Adventure - Comedy - Family,4.1,"$48,000,000",59645,35
14,15.,Dune,(2021),155 min,Action - Adventure - Drama,8.0,"$165,000,000",668781,74
15,16.,Knights of the Zodiac,(2023),112 min,Action - Adventure - Drama,4.7,,1666,
16,17.,M3GAN,(2022),102 min,Horror - Sci-Fi - Thriller,6.4,"$12,000,000",98523,72
17,18.,The Hunger Games,(2012),142 min,Action - Adventure - Sci-Fi,7.2,"$78,000,000",944424,68
18,19.,Wifelike,(2022),105 min,Sci-Fi - Thriller,4.9,,1859,
19,20.,Lilo & Stitch,,,Action - Adventure - Comedy,,,,
20,21.,Guardians of the Galaxy,(2014),121 min,Action - Adventure - Comedy,8.0,"$170,000,000",1204521,76
21,22.,Blade Runner 2049,(2017),164 min,Action - Drama - Mystery,8.0,"$150,000,000",599916,81
22,23.,Superman,(1978),143 min,Action - Adventure - Sci-Fi,7.4,"$55,000,000",180014,82
23,24.,Spider-Man: Across the Spider-Verse,(2023),140 min,Animation - Action - Adventure,,"$150,000,000",,
24,25.,Inception,(2010),148 min,Action - Adventure - Sci-Fi,8.8,"$160,000,000",2404440,74
25,26.,Spider-Man: No Way Home,(2021),148 min,Action - Adventure - Fantasy,8.2,"$200,000,000",790388,71
26,27.,Black Panther: Wakanda Forever,(2022),161 min,Action - Adventure - Drama,6.7,"$250,000,000",262255,67
27,28.,Avengers: Endgame,(2019),181 min,Action - Adventure - Drama,8.4,"$356,000,000",1172691,78
28,29.,Time Trap,(2017),87 min,Action - Adventure - Mystery,6.2,"$1,000,000",39485,46
29,30.,Alien,(1979),117 min,Horror - Sci-Fi,8.5,"$11,000,000",900538,89
30,31.,Avatar,(2009),162 min,Action - Adventure - Fantasy,7.9,"$237,000,000",1339257,83
31,32.,The Black Demon,(2023),100 min,Horror - Sci-Fi - Thriller,4.2,,217,
32,33.,Kraven the Hunter,(2023),,Action - Adventure - Sci-Fi,,,,
33,34.,The Meg 2: The Trench,(2023),,Action - Adventure - Horror,,,,
34,35.,Jurassic Park,(1993),127 min,Action - Adventure - Sci-Fi,8.2,"$63,000,000",1010771,68
35,36.,Spider-Man,(2002),121 min,Action - Adventure - Sci-Fi,7.4,"$139,000,000",835460,73
36,37.,Back to the Future,(1985),116 min,Adventure - Comedy - Sci-Fi,8.5,"$19,000,000",1233826,87
37,38.,Thor: Love and Thunder,(2022),118 min,Action - Adventure - Comedy,6.2,"$250,000,000",359386,57
38,39.,Free Guy,(2021),115 min,Action - Adventure - Comedy,7.1,"$120,000,000",388114,62
39,40.,Jurassic World: Dominion,(2022),147 min,Action - Adventure - Sci-Fi,5.6,"$165,000,000",181974,38
40,41.,The Matrix,(1999),136 min,Action - Sci-Fi,8.7,"$63,000,000",1951521,73
41,42.,Star Wars: Episode IV - A New Hope,(1977),121 min,Action - Adventure - Fantasy,8.6,"$11,000,000",1389357,90
42,43.,Aquaman and the Lost Kingdom,(2023),,Action - Adventure - Fantasy,,"$205,000,000",,
43,44.,Spider-Man: Into the Spider-Verse,(2018),117 min,Animation - Action - Adventure,8.4,"$90,000,000",558545,87
44,45.,The Martian,(2015),144 min,Adventure - Drama - Sci-Fi,8.0,"$108,000,000",876321,80
45,46.,Black Adam,(2022),125 min,Action - Adventure - Fantasy,6.3,"$195,000,000",243239,41
46,47.,Mad Max: Fury Road,(2015),120 min,Action - Adventure - Sci-Fi,8.1,"$150,000,000",1026456,90
47,48.,Guardians of the Galaxy Vol. 2,(2017),136 min,Action - Adventure - Comedy,7.6,"$200,000,000",702605,67
48,49.,Tenet,(2020),150 min,Action - Sci-Fi - Thriller,7.3,"$205,000,000",527423,69
49,50.,Unidentified Objects,(2022),100 min,Comedy - Drama - Sci-Fi,7.2,,87,
50,51.,The Suicide Squad,(2021),132 min,Action - Adventure - Comedy,7.2,"$185,000,000",368823,72
51,52.,Aliens,(1986),137 min,Action - Adventure - Sci-Fi,8.4,"$18,500,000",730567,84
52,53.,Avengers: Infinity War,(2018),149 min,Action - Adventure - Sci-Fi,8.4,"$321,000,000",1116589,68
53,54.,The Hunger Games: Catching Fire,(2013),146 min,Action - Adventure - Sci-Fi,7.5,"$130,000,000",681657,76
54,55.,Don't Look Up,(2021),138 min,Comedy - Drama - Sci-Fi,7.2,"$75,000,000",555473,49

In [4]:
df.info

<bound method DataFrame.info of       Number                                              Title    Year
0         1.  The Hunger Games: The Ballad of Songbirds and ...  (2023)  \
1         2.                                          The Flash  (2023)
2         3.                     Guardians of the Galaxy Vol. 3  (2023)
3         4.                  Ant-Man and the Wasp: Quantumania  (2023)
4         5.                   Transformers: Rise of the Beasts  (2023)
...      ...                                                ...     ...
5721  5,722.                                        Way Station
5722  5,723.                                       Fallen Cards
5723  5,724.                                      Bimbo bambino  (2018)
5724  5,725.                                            Virus X  (2010)
5725  5,726.                                             Gogola  (1966)

      Runtime                           Genre Rating        Budget   Votes
0                Action -  Adventure -  Drama                               \
1              Action -  Adventure -  Fantasy         $200,000,000
2     150 min   Action -  Adventure -  Comedy    8.4                 35997
3     124 min   Action -  Adventure -  Comedy    6.2  $200,000,000  126234
4               Action -  Adventure -  Sci-Fi         $200,000,000
...       ...                             ...    ...           ...     ...
5721                                   Sci-Fi
5722             Action -  Adventure -  Drama           $1,000,000
5723                Action -  Comedy -  Drama    6.4   SEK 100,000      21
5724   85 min                Horror -  Sci-Fi    2.9      $900,000     611
5725                                   Sci-Fi    8.2                    14

     Metascore
0
1
2           65
3           48
4
...        ...
5721
5722
5723
5724
5725

[5726 rows x 9 columns]>

In [5]:
df.describe()

,Number,Title,Year,Runtime,Genre,Rating,Budget,Votes,Metascore
count,5726,5726,5726,5726,5726,5726,5726,5726,5726
unique,5726,5522,191,161,309,90,712,3628,91
top,1.,Dr. Jekyll and Mr. Hyde,,,Horror - Sci-Fi,,,,
freq,1,4,296,530,367,554,3490,554,4358

In [6]:
df.describe().T

          count unique                      top  freq
Number     5726   5726                       1.     1
Title      5726   5522  Dr. Jekyll and Mr. Hyde     4
Year       5726    191                            296
Runtime    5726    161                            530
Genre      5726    309         Horror -  Sci-Fi   367
Rating     5726     90                            554
Budget     5726    712                           3490
Votes      5726   3628                            554
Metascore  5726     91                           4358

In [7]:
df.isnull().sum()

Number       0
Title        0
Year         0
Runtime      0
Genre        0
Rating       0
Budget       0
Votes        0
Metascore    0
dtype: int64

In [9]:
df.isna().sum()

Number       0
Title        0
Year         0
Runtime      0
Genre        0
Rating       0
Budget       0
Votes        0
Metascore    0
dtype: int64

In [12]:
df.isin([""]).sum()

Number          0
Title           0
Year          296
Runtime       530
Genre           0
Rating        554
Budget       3490
Votes         554
Metascore    4358
dtype: int64

In [13]:
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from webdriver_manager.firefox import GeckoDriverManager
from bs4 import BeautifulSoup
import csv
import pandas as pd
import time

options = Options()
options.headless = True
driver = webdriver.Firefox(firefox_binary="C:/Program Files/LibreWolf/librewolf.exe", options=options, executable_path=GeckoDriverManager().install())

df = pd.DataFrame(columns=["Number", "Title", "Year", "Runtime", "Genre", "Rating", "Budget", "Votes", "Metascore"])

url_template = "https://www.imdb.com/search/title/?genres=fantasy&start={}&explore=title_type,genres&title_type=movie&ref_=adv_explore_rhs&language=en"
start = 1
movies = []

# sadece ilk 2 sayfanın verisini almak için döngüyü 2 kez çalıştırıyoruz
for start in range(1, 1001, 50):
    url = url_template.format(start)
    driver.get(url)
    time.sleep(6)
    soup = BeautifulSoup(driver.page_source, 'html.parser')
    
    items = soup.select('.lister-item-content')
    if not items:
        break
        
    df = pd.concat([df, pd.DataFrame({"Number": number, "Title": title, "Year": year, "Runtime": runtime, "Genre": genre, "Rating": rating, "Budget": budget, "Votes": votes, "Metascore": metascore}, index=[0])], ignore_index=True)


    for item in soup.select('.lister-item-content'):
        number = item.select_one('.lister-item-header span').text.strip('()')
        title = item.select_one('.lister-item-header a').text.strip()
        runtime_element = item.select_one('.runtime')
        runtime = runtime_element.text.strip() if runtime_element else ''
        rating_element = item.select_one('.ratings-imdb-rating strong')
        rating = rating_element.text.strip() if rating_element else ''
        year = item.select_one('.lister-item-content .text-muted').text.strip()

        genre_element = item.select_one('.genre')
        genre = " - ".join(genre_element.text.strip().split(',')) if genre_element else ''

        # Metascore bilgisini alınacaktır.
        metascore_element = item.select_one('.metascore')
        metascore = metascore_element.text.strip() if metascore_element else ''


        link = item.select_one('.lister-item-header a')['href']
        driver.get(f"https://www.imdb.com{link}business")
        time.sleep(1)

        soup = BeautifulSoup(driver.page_source, 'html.parser')
            
        # Oyların sayısı alınacaktır.
        votes_element = item.select_one('span[name="nv"]')
        if votes_element:
            votes = votes_element['data-value']
        else:
            votes = ''
        
        # Budget değeri varsa alınacak eğer tahmini varsa o da alınacaktır.
        soup = BeautifulSoup(driver.page_source, 'html.parser')
        budget_elements = soup.findAll('span', {'class': 'ipc-metadata-list-item__list-content-item'})
        budget = ''
        for element in budget_elements:
            text = element.text.strip()
            if text.startswith('$'):
                if any(x in text.lower() for x in ["gross worldwide", "gross us & canada", "opening weekend us & canada"]):
                    continue
                else:
                    if "Budget" in text.lower() or "estimated" in text.lower():
                        budget = text.split(' (')[0]
                        break
                    else:
                        budget = ''
            elif "Budget" in text.lower() or "estimated" in text.lower():
                    budget = text.split(' (')[0]
                    break
            else:
                budget = ''

        df = pd.concat([df, pd.DataFrame({"Number": number, "Title": title, "Year": year, "Runtime": runtime, "Genre": genre, "Rating": rating, "Budget": budget, "Votes": votes, "Metascore": metascore}, index=[0])], ignore_index=True)
        df.to_csv("imdb_scraped_data_fantasy.csv", index=False)
driver.quit()

C:\Users\Sw4yt\AppData\Local\Temp\ipykernel_13136\1649255778.py:13: DeprecationWarning: headless property is deprecated, instead use add_argument('-headless')
  options.headless = True
C:\Users\Sw4yt\AppData\Local\Temp\ipykernel_13136\1649255778.py:14: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Firefox(firefox_binary="C:/Program Files/LibreWolf/librewolf.exe", options=options, executable_path=GeckoDriverManager().install())
C:\Users\Sw4yt\AppData\Local\Temp\ipykernel_13136\1649255778.py:14: DeprecationWarning: firefox_binary has been deprecated, please pass in a Service object
  driver = webdriver.Firefox(firefox_binary="C:/Program Files/LibreWolf/librewolf.exe", options=options, executable_path=GeckoDriverManager().install())

In [ ]:
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from webdriver_manager.firefox import GeckoDriverManager
from bs4 import BeautifulSoup
import csv
import pandas as pd
import time

options = Options()
options.headless = True
driver = webdriver.Firefox(options=options, executable_path=GeckoDriverManager().install())

df = pd.DataFrame(columns=["Number", "Title", "Year", "Runtime", "Genre", "Rating", "Budget", "Votes", "Metascore"])

url_template = "https://www.imdb.com/search/title/?genres=comedy&sort=num_votes,desc&start={}&explore=title_type,genres&title_type=movie&ref_=adv_explore_rhs&language=en"
start = 1
movies = []

# sadece ilk 2 sayfanın verisini almak için döngüyü 2 kez çalıştırıyoruz
for start in range(1, 1001, 50):
    url = url_template.format(start)
    driver.get(url)
    time.sleep(5)
    soup = BeautifulSoup(driver.page_source, 'html.parser')


    items = soup.select('.lister-item-content')
    if not items:
        break
    for item in soup.select('.lister-item-content'):
        number = item.select_one('.lister-item-header span').text.strip('()')
        title = item.select_one('.lister-item-header a').text.strip()
        runtime_element = item.select_one('.runtime')
        runtime = runtime_element.text.strip() if runtime_element else ''
        rating_element = item.select_one('.ratings-imdb-rating strong')
        rating = rating_element.text.strip() if rating_element else ''
        year = item.select_one('.lister-item-content .text-muted').text.strip()
        genre_element = item.select_one('.genre')
        genre = " - ".join(genre_element.text.strip().split(',')) if genre_element else ''

        # Metascore bilgisini alınacaktır.
        metascore_element = item.select_one('.metascore')
        metascore = metascore_element.text.strip() if metascore_element else ''
        link = item.select_one('.lister-item-header a')['href']
        driver.get(f"https://www.imdb.com{link}business")
        time.sleep(1)
        
        soup = BeautifulSoup(driver.page_source, 'html.parser')

        
        # Oyların sayısı alınacaktır.
        votes_element = item.select_one('span[name="nv"]')
        if votes_element:
            votes = votes_element['data-value']
        else:
            votes = ''

    
        # Budget değeri varsa alınacak eğer tahmini varsa o da alınacaktır.
        soup = BeautifulSoup(driver.page_source, 'html.parser')
        budget_elements = soup.findAll('span', {'class': 'ipc-metadata-list-item__list-content-item'})
        budget = ''
        for element in budget_elements:
            text = element.text.strip()
            if text.startswith('$'):
                if any(x in text.lower() for x in ["gross worldwide", "gross us & canada", "opening weekend us & canada"]):
                    continue
                else:
                    if "Budget" in text.lower() or "estimated" in text.lower():
                        budget = text.split(' (')[0]
                        break
                    else:
                        budget = ''
            elif "Budget" in text.lower() or "estimated" in text.lower():
                    budget = text.split(' (')[0]
                    break
            else:
                budget = ''

        df = pd.concat([df, pd.DataFrame({"Number": number, "Title": title, "Year": year, "Runtime": runtime, "Genre": genre, "Rating": rating, "Budget": budget, "Votes": votes, "Metascore": metascore}, index=[0])], ignore_index=True)
        df.to_csv("imdb_scraped_data_comedy.csv", index=False)
driver.quit()

In [18]:
import csv
import pandas as pd

df_1 = pd.read_csv("imdb_scraped_data_scifi.csv")
df_2 = pd.read_csv("imdb_scraped_data_comedy.csv")
df_3 = pd.read_csv("imdb_scraped_data_fantasy.csv")
df_combined = pd.concat([df_1, df_2, df_3])

In [19]:
df_combined

,Number,Title,Year,Runtime,Genre,Rating,Budget,Votes,Metascore
0,1.,The Hunger Games: The Ballad of Songbirds and ...,(2023),NaN,Action - Adventure - Drama,NaN,NaN,NaN,NaN
1,2.,The Flash,(2023),NaN,Action - Adventure - Fantasy,NaN,"$200,000,000",NaN,NaN
2,3.,Guardians of the Galaxy Vol. 3,(2023),150 min,Action - Adventure - Comedy,8.4,NaN,35997.0,65.0
3,4.,Ant-Man and the Wasp: Quantumania,(2023),124 min,Action - Adventure - Comedy,6.2,"$200,000,000",126234.0,48.0
4,5.,Transformers: Rise of the Beasts,(2023),NaN,Action - Adventure - Sci-Fi,NaN,"$200,000,000",NaN,NaN
...,...,...,...,...,...,...,...,...,...
1014,996,Teenage Mutant Ninja Turtles III,-1993,96 min,Action - Adventure - Comedy,4.8,"$21,000,000",34500.0,40.0
1015,997,It's a Boy Girl Thing,-2006,95 min,Comedy - Fantasy - Romance,6.2,"$15,500,000",41972.0,NaN
1016,998,Justice Society: World War II,-2021,84 min,Animation - Action - Adventure,6.4,NaN,8206.0,NaN
1017,999,Warlock,-1989,103 min,Action - Fantasy - Horror,6.2,"$7,000,000",17874.0,44.0
1018,"1,000.00",A Christmas Carol,-2009,96 min,Animation - Adventure - Comedy,6.8,"$200,000,000",122047.0,55.0

In [20]:
df_combined.info

<bound method DataFrame.info of         Number                                              Title    Year
0           1.  The Hunger Games: The Ballad of Songbirds and ...  (2023)  \
1           2.                                          The Flash  (2023)
2           3.                     Guardians of the Galaxy Vol. 3  (2023)
3           4.                  Ant-Man and the Wasp: Quantumania  (2023)
4           5.                   Transformers: Rise of the Beasts  (2023)
...        ...                                                ...     ...
1014       996                   Teenage Mutant Ninja Turtles III   -1993
1015       997                              It's a Boy Girl Thing   -2006
1016       998                      Justice Society: World War II   -2021
1017       999                                            Warlock   -1989
1018  1,000.00                                  A Christmas Carol   -2009

      Runtime                             Genre  Rating         Budget
0         NaN      Action -  Adventure -  Drama     NaN            NaN  \
1         NaN    Action -  Adventure -  Fantasy     NaN   $200,000,000
2     150 min     Action -  Adventure -  Comedy     8.4            NaN
3     124 min     Action -  Adventure -  Comedy     6.2   $200,000,000
4         NaN     Action -  Adventure -  Sci-Fi     NaN   $200,000,000
...       ...                               ...     ...            ...
1014   96 min     Action -  Adventure -  Comedy     4.8   $21,000,000
1015   95 min      Comedy -  Fantasy -  Romance     6.2   $15,500,000
1016   84 min  Animation -  Action -  Adventure     6.4            NaN
1017  103 min       Action -  Fantasy -  Horror     6.2    $7,000,000
1018   96 min  Animation -  Adventure -  Comedy     6.8  $200,000,000

         Votes  Metascore
0          NaN        NaN
1          NaN        NaN
2      35997.0       65.0
3     126234.0       48.0
4          NaN        NaN
...        ...        ...
1014   34500.0       40.0
1015   41972.0        NaN
1016    8206.0        NaN
1017   17874.0       44.0
1018  122047.0       55.0

[7745 rows x 9 columns]>

In [21]:
df_combined.describe()

            Rating         Votes    Metascore
count  7129.000000  7.129000e+03  3196.000000
mean      5.662379  7.611098e+04    55.689612
std       1.483821  1.642855e+05    17.421427
min       1.000000  5.000000e+00     6.000000
25%       4.700000  7.680000e+02    44.000000
50%       5.900000  4.958000e+03    56.000000
75%       6.700000  8.627900e+04    68.000000
max       9.900000  2.404440e+06    99.000000

In [22]:
df_combined.describe().T

,count,mean,std,min,25%,50%,75%,max
Rating,7129.0,5.662379,1.483821,1.0,4.7,5.9,6.7,9.9
Votes,7129.0,76110.975312,164285.459687,5.0,768.0,4958.0,86279.0,2404440.0
Metascore,3196.0,55.689612,17.421427,6.0,44.0,56.0,68.0,99.0

In [23]:
df_combined.isin([""]).sum()

Number       0
Title        0
Year         0
Runtime      0
Genre        0
Rating       0
Budget       0
Votes        0
Metascore    0
dtype: int64

In [24]:
df_combined.isnull().sum()

Number          0
Title           0
Year          307
Runtime       585
Genre           0
Rating        616
Budget       3768
Votes         616
Metascore    4549
dtype: int64