In [1]:
import csv
import pandas as pd

df_1 = pd.read_csv("imdb_scraped_data_action.csv")
df_2 = pd.read_csv("imdb_scraped_data_comedy.csv")
df_3 = pd.read_csv("imdb_scraped_data_crime.csv")
df_4 = pd.read_csv("imdb_scraped_data_drama.csv")
df_5 = pd.read_csv("imdb_scraped_data_horror.csv")
df_6 = pd.read_csv("imdb_scraped_data_thriller.csv")
df_7 = pd.read_csv("imdb_scraped_data_scifi.csv")
df_combined = pd.concat([df_1, df_2, df_3, df_4, df_5, df_6, df_7])

In [2]:
df_combined

,Number,Title,Year,Runtime,Genre,Rating,Budget,Gross US & Canada,Votes,Metascore
0,1.,The Dark Knight,(2008),152 min,Action - Crime - Drama,9.0,"$185,000,000","534,858,444",2710261,84.0
1,2.,Inception,(2010),148 min,Action - Adventure - Sci-Fi,8.8,"$160,000,000","292,576,195",2405851,74.0
2,3.,The Matrix,(1999),136 min,Action - Sci-Fi,8.7,"$63,000,000","171,479,930",1952536,73.0
3,4.,The Lord of the Rings: The Fellowship of the Ring,(2001),178 min,Action - Adventure - Drama,8.8,"$93,000,000","315,544,750",1911195,92.0
4,5.,The Lord of the Rings: The Return of the King,(2003),201 min,Action - Adventure - Drama,9.0,"$94,000,000","377,845,905",1882385,94.0
...,...,...,...,...,...,...,...,...,...,...
56,57.0,World War Z,(2013),116 min,Action - Adventure - Horror,7.0,"$190,000,000","202,359,711",685861,63.0
57,58.0,2001: A Space Odyssey,(1968),149 min,Adventure - Sci-Fi,8.3,"$12,000,000","56,954,992",683552,84.0
58,59.0,The Hunger Games: Catching Fire,(2013),146 min,Action - Adventure - Sci-Fi,7.5,"$130,000,000","424,668,047",682086,76.0
59,60.0,Spider-Man: Homecoming,(2017),133 min,Action - Adventure - Sci-Fi,7.4,"$175,000,000","334,201,140",677261,73.0
60,61.0,Wonder Woman,(2017),141 min,Action - Adventure - Fantasy,7.4,"$149,000,000","412,563,408",672854,76.0

In [3]:
df_combined = df_combined.drop(columns=["Number"])
df_combined

,Title,Year,Runtime,Genre,Rating,Budget,Gross US & Canada,Votes,Metascore
0,The Dark Knight,(2008),152 min,Action - Crime - Drama,9.0,"$185,000,000","534,858,444",2710261,84.0
1,Inception,(2010),148 min,Action - Adventure - Sci-Fi,8.8,"$160,000,000","292,576,195",2405851,74.0
2,The Matrix,(1999),136 min,Action - Sci-Fi,8.7,"$63,000,000","171,479,930",1952536,73.0
3,The Lord of the Rings: The Fellowship of the Ring,(2001),178 min,Action - Adventure - Drama,8.8,"$93,000,000","315,544,750",1911195,92.0
4,The Lord of the Rings: The Return of the King,(2003),201 min,Action - Adventure - Drama,9.0,"$94,000,000","377,845,905",1882385,94.0
...,...,...,...,...,...,...,...,...,...
56,World War Z,(2013),116 min,Action - Adventure - Horror,7.0,"$190,000,000","202,359,711",685861,63.0
57,2001: A Space Odyssey,(1968),149 min,Adventure - Sci-Fi,8.3,"$12,000,000","56,954,992",683552,84.0
58,The Hunger Games: Catching Fire,(2013),146 min,Action - Adventure - Sci-Fi,7.5,"$130,000,000","424,668,047",682086,76.0
59,Spider-Man: Homecoming,(2017),133 min,Action - Adventure - Sci-Fi,7.4,"$175,000,000","334,201,140",677261,73.0
60,Wonder Woman,(2017),141 min,Action - Adventure - Fantasy,7.4,"$149,000,000","412,563,408",672854,76.0

In [4]:
df_combined["Year"] = df_combined["Year"].str.replace(r'\D', '', regex=True).astype(str)
df_combined["Year"] = df_combined["Year"].str.replace(r'', '')
df_combined["Year"] = df_combined["Year"].str.replace(r'I', '', regex=True)
df_combined

,Title,Year,Runtime,Genre,Rating,Budget,Gross US & Canada,Votes,Metascore
0,The Dark Knight,2008,152 min,Action - Crime - Drama,9.0,"$185,000,000","534,858,444",2710261,84.0
1,Inception,2010,148 min,Action - Adventure - Sci-Fi,8.8,"$160,000,000","292,576,195",2405851,74.0
2,The Matrix,1999,136 min,Action - Sci-Fi,8.7,"$63,000,000","171,479,930",1952536,73.0
3,The Lord of the Rings: The Fellowship of the Ring,2001,178 min,Action - Adventure - Drama,8.8,"$93,000,000","315,544,750",1911195,92.0
4,The Lord of the Rings: The Return of the King,2003,201 min,Action - Adventure - Drama,9.0,"$94,000,000","377,845,905",1882385,94.0
...,...,...,...,...,...,...,...,...,...
56,World War Z,2013,116 min,Action - Adventure - Horror,7.0,"$190,000,000","202,359,711",685861,63.0
57,2001: A Space Odyssey,1968,149 min,Adventure - Sci-Fi,8.3,"$12,000,000","56,954,992",683552,84.0
58,The Hunger Games: Catching Fire,2013,146 min,Action - Adventure - Sci-Fi,7.5,"$130,000,000","424,668,047",682086,76.0
59,Spider-Man: Homecoming,2017,133 min,Action - Adventure - Sci-Fi,7.4,"$175,000,000","334,201,140",677261,73.0
60,Wonder Woman,2017,141 min,Action - Adventure - Fantasy,7.4,"$149,000,000","412,563,408",672854,76.0

In [5]:
len(df_combined.loc[df_combined.duplicated(subset =  ["Title", "Rating", "Runtime"]),:])

4883

In [6]:
df_combined.drop_duplicates(subset = ["Title", "Rating", "Runtime"], keep = "first", inplace=True)

In [7]:
df_combined.reset_index(inplace = True)
df_combined

,index,Title,Year,Runtime,Genre,Rating,Budget,Gross US & Canada,Votes,Metascore
0,0,The Dark Knight,2008,152 min,Action - Crime - Drama,9.0,"$185,000,000","534,858,444",2710261,84.0
1,1,Inception,2010,148 min,Action - Adventure - Sci-Fi,8.8,"$160,000,000","292,576,195",2405851,74.0
2,2,The Matrix,1999,136 min,Action - Sci-Fi,8.7,"$63,000,000","171,479,930",1952536,73.0
3,3,The Lord of the Rings: The Fellowship of the Ring,2001,178 min,Action - Adventure - Drama,8.8,"$93,000,000","315,544,750",1911195,92.0
4,4,The Lord of the Rings: The Return of the King,2003,201 min,Action - Adventure - Drama,9.0,"$94,000,000","377,845,905",1882385,94.0
...,...,...,...,...,...,...,...,...,...,...
8092,2995,The Bad Sleep Well,1960,151 min,Crime - Drama - Thriller,8.0,NaN,NaN,13228,NaN
8093,2996,Vavien,2009,100 min,Comedy - Drama - Thriller,7.5,NaN,NaN,13213,NaN
8094,2999,Trapped,2016,105 min,Drama - Thriller,7.5,NaN,NaN,13171,NaN
8095,11,WALLÂ·E,2008,98 min,Animation - Adventure - Family,8.4,"$180,000,000","223,808,164",1139700,95.0
8096,57,2001: A Space Odyssey,1968,149 min,Adventure - Sci-Fi,8.3,"$12,000,000","56,954,992",683552,84.0

In [8]:
df_combined = df_combined.loc[:, ~df_combined.columns.str.contains("index")]
df_combined

,Title,Year,Runtime,Genre,Rating,Budget,Gross US & Canada,Votes,Metascore
0,The Dark Knight,2008,152 min,Action - Crime - Drama,9.0,"$185,000,000","534,858,444",2710261,84.0
1,Inception,2010,148 min,Action - Adventure - Sci-Fi,8.8,"$160,000,000","292,576,195",2405851,74.0
2,The Matrix,1999,136 min,Action - Sci-Fi,8.7,"$63,000,000","171,479,930",1952536,73.0
3,The Lord of the Rings: The Fellowship of the Ring,2001,178 min,Action - Adventure - Drama,8.8,"$93,000,000","315,544,750",1911195,92.0
4,The Lord of the Rings: The Return of the King,2003,201 min,Action - Adventure - Drama,9.0,"$94,000,000","377,845,905",1882385,94.0
...,...,...,...,...,...,...,...,...,...
8092,The Bad Sleep Well,1960,151 min,Crime - Drama - Thriller,8.0,NaN,NaN,13228,NaN
8093,Vavien,2009,100 min,Comedy - Drama - Thriller,7.5,NaN,NaN,13213,NaN
8094,Trapped,2016,105 min,Drama - Thriller,7.5,NaN,NaN,13171,NaN
8095,WALLÂ·E,2008,98 min,Animation - Adventure - Family,8.4,"$180,000,000","223,808,164",1139700,95.0
8096,2001: A Space Odyssey,1968,149 min,Adventure - Sci-Fi,8.3,"$12,000,000","56,954,992",683552,84.0

In [9]:
df_combined.head(15)

,Title,Year,Runtime,Genre,Rating,Budget,Gross US & Canada,Votes,Metascore
0,The Dark Knight,2008,152 min,Action - Crime - Drama,9.0,"$185,000,000","534,858,444",2710261,84.0
1,Inception,2010,148 min,Action - Adventure - Sci-Fi,8.8,"$160,000,000","292,576,195",2405851,74.0
2,The Matrix,1999,136 min,Action - Sci-Fi,8.7,"$63,000,000","171,479,930",1952536,73.0
3,The Lord of the Rings: The Fellowship of the Ring,2001,178 min,Action - Adventure - Drama,8.8,"$93,000,000","315,544,750",1911195,92.0
4,The Lord of the Rings: The Return of the King,2003,201 min,Action - Adventure - Drama,9.0,"$94,000,000","377,845,905",1882385,94.0
5,The Dark Knight Rises,2012,164 min,Action - Drama - Thriller,8.4,"$250,000,000","448,139,099",1737213,78.0
6,The Lord of the Rings: The Two Towers,2002,179 min,Action - Adventure - Drama,8.8,"$94,000,000","342,551,365",1699229,87.0
7,Gladiator,2000,155 min,Action - Adventure - Drama,8.5,"$103,000,000","187,705,427",1531948,67.0
8,Batman Begins,2005,140 min,Action - Crime - Drama,8.2,"$150,000,000","206,852,432",1499318,70.0
9,The Avengers,2012,143 min,Action - Sci-Fi,8.0,"$220,000,000","623,279,547",1412844,69.0
10,Star Wars: Episode IV - A New Hope,1977,121 min,Action - Adventure - Fantasy,8.6,"$11,000,000","322,740,140",1390125,90.0
11,Avatar,2009,162 min,Action - Adventure - Fantasy,7.9,"$237,000,000","760,507,625",1339803,83.0
12,Star Wars: Episode V - The Empire Strikes Back,1980,124 min,Action - Adventure - Fantasy,8.7,"$18,000,000","290,475,067",1317641,82.0
13,Guardians of the Galaxy,2014,121 min,Action - Adventure - Comedy,8.0,"$170,000,000","333,176,600",1207268,76.0
14,LÃ©on: The Professional,1994,110 min,Action - Crime - Drama,8.5,"FRFÂ 115,000,000","19,501,238",1185893,64.0

In [10]:
df_combined.tail(15)

,Title,Year,Runtime,Genre,Rating,Budget,Gross US & Canada,Votes,Metascore
8082,Red Road,2006,113 min,Drama - Mystery - Thriller,6.8,NaN,"153,432",13361,73.0
8083,Manhattan Night,2016,113 min,Crime - Drama - Mystery,6.2,NaN,NaN,13350,44.0
8084,Te3n,2016,136 min,Drama - Mystery - Thriller,7.2,NaN,"258,066",13350,NaN
8085,Table No. 21,2013,108 min,Adventure - Drama - Thriller,7.2,NaN,"31,658",13347,NaN
8086,Ittefaq,2017,105 min,Crime - Mystery - Thriller,7.2,"â‚¹290,000,000","298,032",13346,NaN
8087,Law of Desire,1987,102 min,Comedy - Drama - Thriller,7.1,NaN,NaN,13299,NaN
8088,Arkansas,2020,117 min,Crime - Thriller,6.0,NaN,NaN,13281,55.0
8089,Beyond a Reasonable Doubt,2009,106 min,Crime - Drama - Mystery,5.8,"$25,000,000","32,409",13271,35.0
8090,Roja,1992,137 min,Drama - Romance - Thriller,8.1,NaN,NaN,13250,NaN
8091,My Son,2021,95 min,Crime - Drama - Mystery,6.0,NaN,NaN,13228,NaN
8092,The Bad Sleep Well,1960,151 min,Crime - Drama - Thriller,8.0,NaN,NaN,13228,NaN
8093,Vavien,2009,100 min,Comedy - Drama - Thriller,7.5,NaN,NaN,13213,NaN
8094,Trapped,2016,105 min,Drama - Thriller,7.5,NaN,NaN,13171,NaN
8095,WALLÂ·E,2008,98 min,Animation - Adventure - Family,8.4,"$180,000,000","223,808,164",1139700,95.0
8096,2001: A Space Odyssey,1968,149 min,Adventure - Sci-Fi,8.3,"$12,000,000","56,954,992",683552,84.0

In [11]:
df_combined

,Title,Year,Runtime,Genre,Rating,Budget,Gross US & Canada,Votes,Metascore
0,The Dark Knight,2008,152 min,Action - Crime - Drama,9.0,"$185,000,000","534,858,444",2710261,84.0
1,Inception,2010,148 min,Action - Adventure - Sci-Fi,8.8,"$160,000,000","292,576,195",2405851,74.0
2,The Matrix,1999,136 min,Action - Sci-Fi,8.7,"$63,000,000","171,479,930",1952536,73.0
3,The Lord of the Rings: The Fellowship of the Ring,2001,178 min,Action - Adventure - Drama,8.8,"$93,000,000","315,544,750",1911195,92.0
4,The Lord of the Rings: The Return of the King,2003,201 min,Action - Adventure - Drama,9.0,"$94,000,000","377,845,905",1882385,94.0
...,...,...,...,...,...,...,...,...,...
8092,The Bad Sleep Well,1960,151 min,Crime - Drama - Thriller,8.0,NaN,NaN,13228,NaN
8093,Vavien,2009,100 min,Comedy - Drama - Thriller,7.5,NaN,NaN,13213,NaN
8094,Trapped,2016,105 min,Drama - Thriller,7.5,NaN,NaN,13171,NaN
8095,WALLÂ·E,2008,98 min,Animation - Adventure - Family,8.4,"$180,000,000","223,808,164",1139700,95.0
8096,2001: A Space Odyssey,1968,149 min,Adventure - Sci-Fi,8.3,"$12,000,000","56,954,992",683552,84.0

In [12]:
df_combined = df_combined[df_combined["Year"] != "nan"]
df_combined

,Title,Year,Runtime,Genre,Rating,Budget,Gross US & Canada,Votes,Metascore
0,The Dark Knight,2008,152 min,Action - Crime - Drama,9.0,"$185,000,000","534,858,444",2710261,84.0
1,Inception,2010,148 min,Action - Adventure - Sci-Fi,8.8,"$160,000,000","292,576,195",2405851,74.0
2,The Matrix,1999,136 min,Action - Sci-Fi,8.7,"$63,000,000","171,479,930",1952536,73.0
3,The Lord of the Rings: The Fellowship of the Ring,2001,178 min,Action - Adventure - Drama,8.8,"$93,000,000","315,544,750",1911195,92.0
4,The Lord of the Rings: The Return of the King,2003,201 min,Action - Adventure - Drama,9.0,"$94,000,000","377,845,905",1882385,94.0
...,...,...,...,...,...,...,...,...,...
8092,The Bad Sleep Well,1960,151 min,Crime - Drama - Thriller,8.0,NaN,NaN,13228,NaN
8093,Vavien,2009,100 min,Comedy - Drama - Thriller,7.5,NaN,NaN,13213,NaN
8094,Trapped,2016,105 min,Drama - Thriller,7.5,NaN,NaN,13171,NaN
8095,WALLÂ·E,2008,98 min,Animation - Adventure - Family,8.4,"$180,000,000","223,808,164",1139700,95.0
8096,2001: A Space Odyssey,1968,149 min,Adventure - Sci-Fi,8.3,"$12,000,000","56,954,992",683552,84.0

In [13]:
df_combined = df_combined[df_combined["Year"] != "2024"]
df_combined

,Title,Year,Runtime,Genre,Rating,Budget,Gross US & Canada,Votes,Metascore
0,The Dark Knight,2008,152 min,Action - Crime - Drama,9.0,"$185,000,000","534,858,444",2710261,84.0
1,Inception,2010,148 min,Action - Adventure - Sci-Fi,8.8,"$160,000,000","292,576,195",2405851,74.0
2,The Matrix,1999,136 min,Action - Sci-Fi,8.7,"$63,000,000","171,479,930",1952536,73.0
3,The Lord of the Rings: The Fellowship of the Ring,2001,178 min,Action - Adventure - Drama,8.8,"$93,000,000","315,544,750",1911195,92.0
4,The Lord of the Rings: The Return of the King,2003,201 min,Action - Adventure - Drama,9.0,"$94,000,000","377,845,905",1882385,94.0
...,...,...,...,...,...,...,...,...,...
8092,The Bad Sleep Well,1960,151 min,Crime - Drama - Thriller,8.0,NaN,NaN,13228,NaN
8093,Vavien,2009,100 min,Comedy - Drama - Thriller,7.5,NaN,NaN,13213,NaN
8094,Trapped,2016,105 min,Drama - Thriller,7.5,NaN,NaN,13171,NaN
8095,WALLÂ·E,2008,98 min,Animation - Adventure - Family,8.4,"$180,000,000","223,808,164",1139700,95.0
8096,2001: A Space Odyssey,1968,149 min,Adventure - Sci-Fi,8.3,"$12,000,000","56,954,992",683552,84.0

In [14]:
df_combined = df_combined.dropna(subset=["Runtime"])
df_combined.reset_index(inplace = True)
df_combined

,index,Title,Year,Runtime,Genre,Rating,Budget,Gross US & Canada,Votes,Metascore
0,0,The Dark Knight,2008,152 min,Action - Crime - Drama,9.0,"$185,000,000","534,858,444",2710261,84.0
1,1,Inception,2010,148 min,Action - Adventure - Sci-Fi,8.8,"$160,000,000","292,576,195",2405851,74.0
2,2,The Matrix,1999,136 min,Action - Sci-Fi,8.7,"$63,000,000","171,479,930",1952536,73.0
3,3,The Lord of the Rings: The Fellowship of the Ring,2001,178 min,Action - Adventure - Drama,8.8,"$93,000,000","315,544,750",1911195,92.0
4,4,The Lord of the Rings: The Return of the King,2003,201 min,Action - Adventure - Drama,9.0,"$94,000,000","377,845,905",1882385,94.0
...,...,...,...,...,...,...,...,...,...,...
8091,8092,The Bad Sleep Well,1960,151 min,Crime - Drama - Thriller,8.0,NaN,NaN,13228,NaN
8092,8093,Vavien,2009,100 min,Comedy - Drama - Thriller,7.5,NaN,NaN,13213,NaN
8093,8094,Trapped,2016,105 min,Drama - Thriller,7.5,NaN,NaN,13171,NaN
8094,8095,WALLÂ·E,2008,98 min,Animation - Adventure - Family,8.4,"$180,000,000","223,808,164",1139700,95.0
8095,8096,2001: A Space Odyssey,1968,149 min,Adventure - Sci-Fi,8.3,"$12,000,000","56,954,992",683552,84.0

In [15]:
df_combined = df_combined.loc[:, ~df_combined.columns.str.contains("index")]
df_combined

,Title,Year,Runtime,Genre,Rating,Budget,Gross US & Canada,Votes,Metascore
0,The Dark Knight,2008,152 min,Action - Crime - Drama,9.0,"$185,000,000","534,858,444",2710261,84.0
1,Inception,2010,148 min,Action - Adventure - Sci-Fi,8.8,"$160,000,000","292,576,195",2405851,74.0
2,The Matrix,1999,136 min,Action - Sci-Fi,8.7,"$63,000,000","171,479,930",1952536,73.0
3,The Lord of the Rings: The Fellowship of the Ring,2001,178 min,Action - Adventure - Drama,8.8,"$93,000,000","315,544,750",1911195,92.0
4,The Lord of the Rings: The Return of the King,2003,201 min,Action - Adventure - Drama,9.0,"$94,000,000","377,845,905",1882385,94.0
...,...,...,...,...,...,...,...,...,...
8091,The Bad Sleep Well,1960,151 min,Crime - Drama - Thriller,8.0,NaN,NaN,13228,NaN
8092,Vavien,2009,100 min,Comedy - Drama - Thriller,7.5,NaN,NaN,13213,NaN
8093,Trapped,2016,105 min,Drama - Thriller,7.5,NaN,NaN,13171,NaN
8094,WALLÂ·E,2008,98 min,Animation - Adventure - Family,8.4,"$180,000,000","223,808,164",1139700,95.0
8095,2001: A Space Odyssey,1968,149 min,Adventure - Sci-Fi,8.3,"$12,000,000","56,954,992",683552,84.0

In [16]:
A = ["Budget", "Metascore", "Gross US & Canada"]
en_az_bir_bos_hucre_sayisi = df_combined[A].isnull().any(axis=1).sum()
print(en_az_bir_bos_hucre_sayisi)

3056

In [17]:
bos_satirlar = df_combined[df_combined[A].isna().any(axis=1)]
print(len(bos_satirlar))

3056

In [18]:
Nan_delete = ["Budget", "Metascore", "Gross US & Canada"]
df_combined = df_combined.dropna(subset = Nan_delete)

In [19]:
df_combined.isnull().sum()

Title                0
Year                 0
Runtime              0
Genre                0
Rating               0
Budget               0
Gross US & Canada    0
Votes                0
Metascore            0
dtype: int64

In [20]:
df_combined.shape

(5040, 9)

In [21]:
df_combined = df_combined .drop(df_combined[~df_combined["Budget"].str.startswith("$")].index)
df_combined

,Title,Year,Runtime,Genre,Rating,Budget,Gross US & Canada,Votes,Metascore
0,The Dark Knight,2008,152 min,Action - Crime - Drama,9.0,"$185,000,000","534,858,444",2710261,84.0
1,Inception,2010,148 min,Action - Adventure - Sci-Fi,8.8,"$160,000,000","292,576,195",2405851,74.0
2,The Matrix,1999,136 min,Action - Sci-Fi,8.7,"$63,000,000","171,479,930",1952536,73.0
3,The Lord of the Rings: The Fellowship of the Ring,2001,178 min,Action - Adventure - Drama,8.8,"$93,000,000","315,544,750",1911195,92.0
4,The Lord of the Rings: The Return of the King,2003,201 min,Action - Adventure - Drama,9.0,"$94,000,000","377,845,905",1882385,94.0
...,...,...,...,...,...,...,...,...,...
8058,The Crossing Guard,1995,111 min,Drama - Thriller,6.3,"$9,000,000","832,910",14017,46.0
8068,Owning Mahowny,2003,104 min,Crime - Drama - Thriller,7.0,"$10,000,000","1,011,054",13778,70.0
8088,Beyond a Reasonable Doubt,2009,106 min,Crime - Drama - Mystery,5.8,"$25,000,000","32,409",13271,35.0
8094,WALLÂ·E,2008,98 min,Animation - Adventure - Family,8.4,"$180,000,000","223,808,164",1139700,95.0
8095,2001: A Space Odyssey,1968,149 min,Adventure - Sci-Fi,8.3,"$12,000,000","56,954,992",683552,84.0

In [22]:
df_combined.shape

(4852, 9)

In [23]:
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4852 entries, 0 to 8095
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Title              4852 non-null   object
 1   Year               4852 non-null   object
 2   Runtime            4852 non-null   object
 3   Genre              4852 non-null   object
 4   Rating             4852 non-null   float64
 5   Budget             4852 non-null   object
 6   Gross US & Canada  4852 non-null   object
 7   Votes              4852 non-null   int64
 8   Metascore          4852 non-null   float64
dtypes: float64(2), int64(1), object(6)
memory usage: 379.1+ KB

In [24]:
df_combined["Year"] = df_combined["Year"].astype("int64")

In [25]:
df_combined['Runtime'] = df_combined["Runtime"].str.replace(" min", "").astype("int64")

In [26]:
df_combined["Budget"] = df_combined["Budget"].str.replace("$", "").str.replace(",", "").astype("float64")

In [27]:
df_combined["Gross US & Canada"] = df_combined["Gross US & Canada"].str.replace(",", "").astype('float64')

In [28]:
df_combined.reset_index(drop=True, inplace=True)

In [29]:
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4852 entries, 0 to 4851
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Title              4852 non-null   object
 1   Year               4852 non-null   int64
 2   Runtime            4852 non-null   int64
 3   Genre              4852 non-null   object
 4   Rating             4852 non-null   float64
 5   Budget             4852 non-null   float64
 6   Gross US & Canada  4852 non-null   float64
 7   Votes              4852 non-null   int64
 8   Metascore          4852 non-null   float64
dtypes: float64(4), int64(3), object(2)
memory usage: 341.3+ KB

In [36]:
df_combined.nunique()

Title                4747
Year                   90
Runtime               131
Genre                 306
Rating                 71
Budget                422
Gross US & Canada    4802
Votes                4806
Metascore              92
dtype: int64

In [37]:
print(df_combined["Genre"].value_counts().head(10))

Genre
Comedy -  Drama -  Romance          242
Action -  Crime -  Drama            167
Comedy -  Drama                     164
Animation -  Adventure -  Comedy    156
Action -  Adventure -  Sci-Fi       129
Action -  Adventure -  Comedy       125
Comedy                              121
Drama -  Romance                    108
Drama                               108
Crime -  Drama -  Thriller          106
Name: count, dtype: int64

In [31]:
df_combined.to_csv("imdb_scraped_data_all.csv", index=False)