In [1]:
import csv
import pandas as pd

df_1 = pd.read_csv("imdb_scraped_data_scifi.csv")
df_2 = pd.read_csv("imdb_scraped_data_comedy.csv")
df_3 = pd.read_csv("imdb_scraped_data_fantasy.csv")
df_combined = pd.concat([df_1, df_2, df_3])

In [2]:
df_combined

,Number,Title,Year,Runtime,Genre,Rating,Budget,Votes,Metascore
0,1.,The Hunger Games: The Ballad of Songbirds and ...,(2023),NaN,Action - Adventure - Drama,NaN,NaN,NaN,NaN
1,2.,The Flash,(2023),NaN,Action - Adventure - Fantasy,NaN,"$200,000,000",NaN,NaN
2,3.,Guardians of the Galaxy Vol. 3,(2023),150 min,Action - Adventure - Comedy,8.4,NaN,35997.0,65.0
3,4.,Ant-Man and the Wasp: Quantumania,(2023),124 min,Action - Adventure - Comedy,6.2,"$200,000,000",126234.0,48.0
4,5.,Transformers: Rise of the Beasts,(2023),NaN,Action - Adventure - Sci-Fi,NaN,"$200,000,000",NaN,NaN
...,...,...,...,...,...,...,...,...,...
1014,996,Teenage Mutant Ninja Turtles III,-1993,96 min,Action - Adventure - Comedy,4.8,"$21,000,000",34500.0,40.0
1015,997,It's a Boy Girl Thing,-2006,95 min,Comedy - Fantasy - Romance,6.2,"$15,500,000",41972.0,NaN
1016,998,Justice Society: World War II,-2021,84 min,Animation - Action - Adventure,6.4,NaN,8206.0,NaN
1017,999,Warlock,-1989,103 min,Action - Fantasy - Horror,6.2,"$7,000,000",17874.0,44.0
1018,"1,000.00",A Christmas Carol,-2009,96 min,Animation - Adventure - Comedy,6.8,"$200,000,000",122047.0,55.0

In [3]:
len(df_combined.loc[df_combined.duplicated(subset =  ["Title", "Rating", "Runtime"]),:])

508

In [4]:
df_combined.drop_duplicates(subset = ["Title", "Rating", "Runtime"], keep = "first", inplace=True)

In [5]:
df_combined.reset_index(inplace = True)
df_combined

,index,Number,Title,Year,Runtime,Genre,Rating,Budget,Votes,Metascore
0,0,1.,The Hunger Games: The Ballad of Songbirds and ...,(2023),NaN,Action - Adventure - Drama,NaN,NaN,NaN,NaN
1,1,2.,The Flash,(2023),NaN,Action - Adventure - Fantasy,NaN,"$200,000,000",NaN,NaN
2,2,3.,Guardians of the Galaxy Vol. 3,(2023),150 min,Action - Adventure - Comedy,8.4,NaN,35997.0,65.0
3,3,4.,Ant-Man and the Wasp: Quantumania,(2023),124 min,Action - Adventure - Comedy,6.2,"$200,000,000",126234.0,48.0
4,4,5.,Transformers: Rise of the Beasts,(2023),NaN,Action - Adventure - Sci-Fi,NaN,"$200,000,000",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
7232,1011,993,The Little Vampire,-2000,95 min,Adventure - Comedy - Family,5.7,"$35,000,000",10890.0,45.0
7233,1012,994,The Legend of Hercules,-2014,99 min,Action - Adventure - Fantasy,4.2,"$70,000,000",55237.0,22.0
7234,1013,995,Needful Things,-1993,120 min,Crime - Drama - Fantasy,6.2,NaN,26178.0,43.0
7235,1015,997,It's a Boy Girl Thing,-2006,95 min,Comedy - Fantasy - Romance,6.2,"$15,500,000",41972.0,NaN
7236,1017,999,Warlock,-1989,103 min,Action - Fantasy - Horror,6.2,"$7,000,000",17874.0,44.0

In [6]:
df_combined = df_combined.loc[:, ~df_combined.columns.str.contains("index")]
df_combined

,Number,Title,Year,Runtime,Genre,Rating,Budget,Votes,Metascore
0,1.,The Hunger Games: The Ballad of Songbirds and ...,(2023),NaN,Action - Adventure - Drama,NaN,NaN,NaN,NaN
1,2.,The Flash,(2023),NaN,Action - Adventure - Fantasy,NaN,"$200,000,000",NaN,NaN
2,3.,Guardians of the Galaxy Vol. 3,(2023),150 min,Action - Adventure - Comedy,8.4,NaN,35997.0,65.0
3,4.,Ant-Man and the Wasp: Quantumania,(2023),124 min,Action - Adventure - Comedy,6.2,"$200,000,000",126234.0,48.0
4,5.,Transformers: Rise of the Beasts,(2023),NaN,Action - Adventure - Sci-Fi,NaN,"$200,000,000",NaN,NaN
...,...,...,...,...,...,...,...,...,...
7232,993,The Little Vampire,-2000,95 min,Adventure - Comedy - Family,5.7,"$35,000,000",10890.0,45.0
7233,994,The Legend of Hercules,-2014,99 min,Action - Adventure - Fantasy,4.2,"$70,000,000",55237.0,22.0
7234,995,Needful Things,-1993,120 min,Crime - Drama - Fantasy,6.2,NaN,26178.0,43.0
7235,997,It's a Boy Girl Thing,-2006,95 min,Comedy - Fantasy - Romance,6.2,"$15,500,000",41972.0,NaN
7236,999,Warlock,-1989,103 min,Action - Fantasy - Horror,6.2,"$7,000,000",17874.0,44.0

In [7]:
df_combined = df_combined.drop(columns=["Number"])
df_combined

,Title,Year,Runtime,Genre,Rating,Budget,Votes,Metascore
0,The Hunger Games: The Ballad of Songbirds and ...,(2023),NaN,Action - Adventure - Drama,NaN,NaN,NaN,NaN
1,The Flash,(2023),NaN,Action - Adventure - Fantasy,NaN,"$200,000,000",NaN,NaN
2,Guardians of the Galaxy Vol. 3,(2023),150 min,Action - Adventure - Comedy,8.4,NaN,35997.0,65.0
3,Ant-Man and the Wasp: Quantumania,(2023),124 min,Action - Adventure - Comedy,6.2,"$200,000,000",126234.0,48.0
4,Transformers: Rise of the Beasts,(2023),NaN,Action - Adventure - Sci-Fi,NaN,"$200,000,000",NaN,NaN
...,...,...,...,...,...,...,...,...
7232,The Little Vampire,-2000,95 min,Adventure - Comedy - Family,5.7,"$35,000,000",10890.0,45.0
7233,The Legend of Hercules,-2014,99 min,Action - Adventure - Fantasy,4.2,"$70,000,000",55237.0,22.0
7234,Needful Things,-1993,120 min,Crime - Drama - Fantasy,6.2,NaN,26178.0,43.0
7235,It's a Boy Girl Thing,-2006,95 min,Comedy - Fantasy - Romance,6.2,"$15,500,000",41972.0,NaN
7236,Warlock,-1989,103 min,Action - Fantasy - Horror,6.2,"$7,000,000",17874.0,44.0

In [8]:
df_combined.head(15)

,Title,Year,Runtime,Genre,Rating,Budget,Votes,Metascore
0,The Hunger Games: The Ballad of Songbirds and ...,(2023),NaN,Action - Adventure - Drama,NaN,NaN,NaN,NaN
1,The Flash,(2023),NaN,Action - Adventure - Fantasy,NaN,"$200,000,000",NaN,NaN
2,Guardians of the Galaxy Vol. 3,(2023),150 min,Action - Adventure - Comedy,8.4,NaN,35997.0,65.0
3,Ant-Man and the Wasp: Quantumania,(2023),124 min,Action - Adventure - Comedy,6.2,"$200,000,000",126234.0,48.0
4,Transformers: Rise of the Beasts,(2023),NaN,Action - Adventure - Sci-Fi,NaN,"$200,000,000",NaN,NaN
5,Avatar: The Way of Water,(2022),192 min,Action - Adventure - Fantasy,7.7,"$350,000,000",372123.0,67.0
6,Mighty Morphin Power Rangers: Once & Always,(2023),55 min,Action - Adventure - Family,5.8,NaN,4766.0,61.0
7,Everything Everywhere All at Once,(2022),139 min,Action - Adventure - Comedy,7.9,"$14,300,000",438661.0,81.0
8,65,(2023),93 min,Action - Adventure - Drama,5.4,"$45,000,000",39416.0,40.0
9,Nope,(2022),130 min,Horror - Mystery - Sci-Fi,6.8,"$68,000,000",224352.0,77.0
10,Dune: Part Two,(2023),NaN,Action - Adventure - Drama,NaN,NaN,NaN,NaN
11,Infinity Pool,(2023),117 min,Crime - Horror - Mystery,6.1,NaN,28331.0,72.0
12,Interstellar,(2014),169 min,Adventure - Drama - Sci-Fi,8.6,"$165,000,000",1899414.0,74.0
13,Super Mario Bros.,(1993),104 min,Adventure - Comedy - Family,4.1,"$48,000,000",59645.0,35.0
14,Dune,(2021),155 min,Action - Adventure - Drama,8.0,"$165,000,000",668781.0,74.0

In [9]:
df_combined.tail(15)

,Title,Year,Runtime,Genre,Rating,Budget,Votes,Metascore
7222,Nine Days,-2020,124 min,Drama - Fantasy,6.8,NaN,9455.0,72.0
7223,A Whisker Away,-2020,104 min,Animation - Adventure - Drama,6.7,NaN,11770.0,NaN
7224,Street Fighter: The Legend of Chun-Li,-2009,96 min,Action - Crime - Fantasy,3.7,"$18,000,000",24546.0,17.0
7225,We're Back! A Dinosaur's Story,-1993,72 min,Animation - Adventure - Comedy,6.0,NaN,15539.0,NaN
7226,Interstate 60: Episodes of the Road,-2002,116 min,Adventure - Comedy - Drama,7.6,"$7,000,000",34527.0,NaN
7227,The Ant Bully,-2006,88 min,Animation - Adventure - Comedy,5.8,"$50,000,000",40563.0,59.0
7228,Freddy's Dead: The Final Nightmare,-1991,89 min,Fantasy - Horror,4.7,"$11,000,000",48497.0,39.0
7229,An American Werewolf in Paris,-1997,98 min,Comedy - Fantasy - Horror,5.1,"$25,000,000",26029.0,31.0
7230,Black Knight,-2001,95 min,Adventure - Comedy - Fantasy,4.9,"$50,000,000",41971.0,32.0
7231,Something Wicked This Way Comes,-1983,95 min,Fantasy - Mystery - Thriller,6.7,"$19,000,000",9968.0,NaN
7232,The Little Vampire,-2000,95 min,Adventure - Comedy - Family,5.7,"$35,000,000",10890.0,45.0
7233,The Legend of Hercules,-2014,99 min,Action - Adventure - Fantasy,4.2,"$70,000,000",55237.0,22.0
7234,Needful Things,-1993,120 min,Crime - Drama - Fantasy,6.2,NaN,26178.0,43.0
7235,It's a Boy Girl Thing,-2006,95 min,Comedy - Fantasy - Romance,6.2,"$15,500,000",41972.0,NaN
7236,Warlock,-1989,103 min,Action - Fantasy - Horror,6.2,"$7,000,000",17874.0,44.0

In [10]:
df_combined["Year"] = df_combined["Year"].str.replace(r'\D', '', regex=True).astype(str)
df_combined["Year"] = df_combined["Year"].str.replace(r'', '')
df_combined["Year"] = df_combined["Year"].str.replace(r'I', '', regex=True)

In [11]:
df_combined

,Title,Year,Runtime,Genre,Rating,Budget,Votes,Metascore
0,The Hunger Games: The Ballad of Songbirds and ...,2023,NaN,Action - Adventure - Drama,NaN,NaN,NaN,NaN
1,The Flash,2023,NaN,Action - Adventure - Fantasy,NaN,"$200,000,000",NaN,NaN
2,Guardians of the Galaxy Vol. 3,2023,150 min,Action - Adventure - Comedy,8.4,NaN,35997.0,65.0
3,Ant-Man and the Wasp: Quantumania,2023,124 min,Action - Adventure - Comedy,6.2,"$200,000,000",126234.0,48.0
4,Transformers: Rise of the Beasts,2023,NaN,Action - Adventure - Sci-Fi,NaN,"$200,000,000",NaN,NaN
...,...,...,...,...,...,...,...,...
7232,The Little Vampire,2000,95 min,Adventure - Comedy - Family,5.7,"$35,000,000",10890.0,45.0
7233,The Legend of Hercules,2014,99 min,Action - Adventure - Fantasy,4.2,"$70,000,000",55237.0,22.0
7234,Needful Things,1993,120 min,Crime - Drama - Fantasy,6.2,NaN,26178.0,43.0
7235,It's a Boy Girl Thing,2006,95 min,Comedy - Fantasy - Romance,6.2,"$15,500,000",41972.0,NaN
7236,Warlock,1989,103 min,Action - Fantasy - Horror,6.2,"$7,000,000",17874.0,44.0

In [12]:
df_combined = df_combined[df_combined["Year"] != "nan"]
df_combined

,Title,Year,Runtime,Genre,Rating,Budget,Votes,Metascore
0,The Hunger Games: The Ballad of Songbirds and ...,2023,NaN,Action - Adventure - Drama,NaN,NaN,NaN,NaN
1,The Flash,2023,NaN,Action - Adventure - Fantasy,NaN,"$200,000,000",NaN,NaN
2,Guardians of the Galaxy Vol. 3,2023,150 min,Action - Adventure - Comedy,8.4,NaN,35997.0,65.0
3,Ant-Man and the Wasp: Quantumania,2023,124 min,Action - Adventure - Comedy,6.2,"$200,000,000",126234.0,48.0
4,Transformers: Rise of the Beasts,2023,NaN,Action - Adventure - Sci-Fi,NaN,"$200,000,000",NaN,NaN
...,...,...,...,...,...,...,...,...
7232,The Little Vampire,2000,95 min,Adventure - Comedy - Family,5.7,"$35,000,000",10890.0,45.0
7233,The Legend of Hercules,2014,99 min,Action - Adventure - Fantasy,4.2,"$70,000,000",55237.0,22.0
7234,Needful Things,1993,120 min,Crime - Drama - Fantasy,6.2,NaN,26178.0,43.0
7235,It's a Boy Girl Thing,2006,95 min,Comedy - Fantasy - Romance,6.2,"$15,500,000",41972.0,NaN
7236,Warlock,1989,103 min,Action - Fantasy - Horror,6.2,"$7,000,000",17874.0,44.0

In [13]:
df_combined = df_combined[df_combined["Year"] != "2024"]
df_combined

,Title,Year,Runtime,Genre,Rating,Budget,Votes,Metascore
0,The Hunger Games: The Ballad of Songbirds and ...,2023,NaN,Action - Adventure - Drama,NaN,NaN,NaN,NaN
1,The Flash,2023,NaN,Action - Adventure - Fantasy,NaN,"$200,000,000",NaN,NaN
2,Guardians of the Galaxy Vol. 3,2023,150 min,Action - Adventure - Comedy,8.4,NaN,35997.0,65.0
3,Ant-Man and the Wasp: Quantumania,2023,124 min,Action - Adventure - Comedy,6.2,"$200,000,000",126234.0,48.0
4,Transformers: Rise of the Beasts,2023,NaN,Action - Adventure - Sci-Fi,NaN,"$200,000,000",NaN,NaN
...,...,...,...,...,...,...,...,...
7232,The Little Vampire,2000,95 min,Adventure - Comedy - Family,5.7,"$35,000,000",10890.0,45.0
7233,The Legend of Hercules,2014,99 min,Action - Adventure - Fantasy,4.2,"$70,000,000",55237.0,22.0
7234,Needful Things,1993,120 min,Crime - Drama - Fantasy,6.2,NaN,26178.0,43.0
7235,It's a Boy Girl Thing,2006,95 min,Comedy - Fantasy - Romance,6.2,"$15,500,000",41972.0,NaN
7236,Warlock,1989,103 min,Action - Fantasy - Horror,6.2,"$7,000,000",17874.0,44.0

In [14]:
df_combined = df_combined.dropna(subset=["Runtime"])
df_combined.reset_index(inplace = True)
df_combined

,index,Title,Year,Runtime,Genre,Rating,Budget,Votes,Metascore
0,2,Guardians of the Galaxy Vol. 3,2023,150 min,Action - Adventure - Comedy,8.4,NaN,35997.0,65.0
1,3,Ant-Man and the Wasp: Quantumania,2023,124 min,Action - Adventure - Comedy,6.2,"$200,000,000",126234.0,48.0
2,5,Avatar: The Way of Water,2022,192 min,Action - Adventure - Fantasy,7.7,"$350,000,000",372123.0,67.0
3,6,Mighty Morphin Power Rangers: Once & Always,2023,55 min,Action - Adventure - Family,5.8,NaN,4766.0,61.0
4,7,Everything Everywhere All at Once,2022,139 min,Action - Adventure - Comedy,7.9,"$14,300,000",438661.0,81.0
...,...,...,...,...,...,...,...,...,...
6643,7232,The Little Vampire,2000,95 min,Adventure - Comedy - Family,5.7,"$35,000,000",10890.0,45.0
6644,7233,The Legend of Hercules,2014,99 min,Action - Adventure - Fantasy,4.2,"$70,000,000",55237.0,22.0
6645,7234,Needful Things,1993,120 min,Crime - Drama - Fantasy,6.2,NaN,26178.0,43.0
6646,7235,It's a Boy Girl Thing,2006,95 min,Comedy - Fantasy - Romance,6.2,"$15,500,000",41972.0,NaN
6647,7236,Warlock,1989,103 min,Action - Fantasy - Horror,6.2,"$7,000,000",17874.0,44.0

In [15]:
df_combined = df_combined.loc[:, ~df_combined.columns.str.contains("index")]
df_combined

,Title,Year,Runtime,Genre,Rating,Budget,Votes,Metascore
0,Guardians of the Galaxy Vol. 3,2023,150 min,Action - Adventure - Comedy,8.4,NaN,35997.0,65.0
1,Ant-Man and the Wasp: Quantumania,2023,124 min,Action - Adventure - Comedy,6.2,"$200,000,000",126234.0,48.0
2,Avatar: The Way of Water,2022,192 min,Action - Adventure - Fantasy,7.7,"$350,000,000",372123.0,67.0
3,Mighty Morphin Power Rangers: Once & Always,2023,55 min,Action - Adventure - Family,5.8,NaN,4766.0,61.0
4,Everything Everywhere All at Once,2022,139 min,Action - Adventure - Comedy,7.9,"$14,300,000",438661.0,81.0
...,...,...,...,...,...,...,...,...
6643,The Little Vampire,2000,95 min,Adventure - Comedy - Family,5.7,"$35,000,000",10890.0,45.0
6644,The Legend of Hercules,2014,99 min,Action - Adventure - Fantasy,4.2,"$70,000,000",55237.0,22.0
6645,Needful Things,1993,120 min,Crime - Drama - Fantasy,6.2,NaN,26178.0,43.0
6646,It's a Boy Girl Thing,2006,95 min,Comedy - Fantasy - Romance,6.2,"$15,500,000",41972.0,NaN
6647,Warlock,1989,103 min,Action - Fantasy - Horror,6.2,"$7,000,000",17874.0,44.0

In [16]:
df_combined.to_csv("imdb_scraped_data_all.csv", index=False)